// scoreConstants.js
export const SCORE = {
  INTENT_BONUS: 10,
  OCCUPATION_BONUS: 10,
  EDUCATION_BONUS: 5,
  STATE_BONUS: 5,
  TAG_BONUS: 3,
};

export const INTENT_CATEGORY_MAP = {
  farmer: ["agriculture", "rural", "environment"],
  scholarship: ["education", "learning", "scholarship"],
  student: ["education", "learning"],
  treatment: ["health", "medical", "wellness"],
  medical: ["health", "medical"],
  "widow-support": ["social welfare", "women", "child"],
  maternity: ["health", "women", "child"],
  disability: ["social welfare", "health"],
  loan: ["banking", "financial", "insurance"],
  "startup-funding": ["business", "entrepreneurship"],
  business: ["business", "entrepreneurship"],
  job: ["skills", "employment"],
  unemployed: ["skills", "employment"],
  housing: ["housing", "shelter", "urban", "rural"],
  sanitation: ["sanitation", "utility", "health"],
  pension: ["social welfare", "senior"],
  marriage: ["social welfare", "women", "child"],
  death: ["social welfare"],
};

export const INTENT_TAG_MAP = {
  farmer: ["kisan", "krishak", "agriculture"],
  scholarship: ["scholarship", "education", "fee"],
  student: ["student", "education"],
  treatment: ["health", "medical", "hospital", "treatment"],
  medical: ["health", "medical", "treatment"],
  "widow-support": ["widow", "vidhwa"],
  maternity: ["maternity", "pregnancy"],
  disability: ["disability", "divyang", "pwd"],
  loan: ["loan", "credit", "mudra"],
  "startup-funding": ["startup", "business", "entrepreneur"],
  business: ["business", "entrepreneur"],
  job: ["job", "employment", "rojgaar"],
  unemployed: ["job", "employment"],
  housing: ["housing", "awas", "shelter"],
  sanitation: ["sanitation", "toilet", "swachh"],
  pension: ["pension", "senior"],
  marriage: ["marriage", "vivah", "wedding"],
  death: ["death", "demise"],
};